"""Fields Added According to user

Revision ID: 5286a64ff73a
Revises: e521577cefc3
Create Date: 2023-10-02 01:41:10.881722

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5286a64ff73a'
down_revision = 'e521577cefc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=28), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=28), nullable=False))
        batch_op.add_column(sa.Column('cnic_number', sa.String(length=28), nullable=False))
        batch_op.add_column(sa.Column('phone_number', sa.String(length=28), nullable=False))
        batch_op.drop_index('username')
        batch_op.create_unique_constraint(None, ['last_name'])
        batch_op.create_unique_constraint(None, ['first_name'])
        batch_op.drop_column('password')
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', mysql.VARCHAR(length=28), nullable=False))
        batch_op.add_column(sa.Column('password', mysql.VARCHAR(length=28), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('username', ['username'], unique=False)
        batch_op.drop_column('phone_number')
        batch_op.drop_column('cnic_number')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
