"""Adding Mosuque Model

Revision ID: d3f79d8253cb
Revises: 5286a64ff73a
Create Date: 2023-10-15 03:04:01.178654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3f79d8253cb'
down_revision = '5286a64ff73a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('first_name')
        batch_op.drop_index('last_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('last_name', ['last_name'], unique=False)
        batch_op.create_index('first_name', ['first_name'], unique=False)

    # ### end Alembic commands ###
