"""Adding Mosuque

Revision ID: f3401b281758
Revises: d3f79d8253cb
Create Date: 2023-10-15 03:11:07.479189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3401b281758'
down_revision = 'd3f79d8253cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mosques',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=28), nullable=False),
    sa.Column('mosque_name', sa.String(length=28), nullable=False),
    sa.Column('mosque_address', sa.String(length=28), nullable=False),
    sa.Column('password', sa.String(length=28), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mosques')
    # ### end Alembic commands ###
